spring:
  output:
    ansi:
      enabled: ALWAYS

  cloud:
    config:
      override-system-properties: false

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_INSTANCE:localhost}:${DISCOVERY_SERVICE_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    git:
      mode: full

server:
  shutdown: graceful