name: "Microservies"

services:
  config-service:
    image: dawid0604/pcforum-config-service-application
    container_name: config-service
    restart: unless-stopped
    environment:
      - DISCOVERY_SERVICE_INSTANCE=discovery-service
      - CONFIG_SERVICE_PORT=${CONFIG_SERVICE_PORT}
      - SERVER_PORT=${CONFIG_SERVICE_PORT}

    healthcheck:
      test: "curl --fail --silent localhost:${CONFIG_SERVICE_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

    networks:
      - pcforum_network

  discovery-service:
    image: dawid0604/pcforum-discovery-service-application
    container_name: discovery-service
    restart: unless-stopped
    environment:
      - CONFIG_SERVICE_INSTANCE=config-service
      - DISCOVERY_SERVICE_PORT=${DISCOVERY_SERVICE_PORT}
      - SERVER_PORT=${DISCOVERY_SERVICE_PORT}
      - CONFIG_SERVICE_PORT=${CONFIG_SERVICE_PORT}

    depends_on:
      config-service:
        condition: service_healthy

    healthcheck:
      test: "curl --fail --silent localhost:${DISCOVERY_SERVICE_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

    networks:
      - pcforum_network

  user-service:
    image: dawid0604/pcforum-user-service-application
    container_name: user-service
    environment:
      - CONFIG_SERVICE_INSTANCE=config-service
      - CONFIG_SERVICE_PORT=${CONFIG_SERVICE_PORT}
      - DISCOVERY_SERVICE_INSTANCE=discovery-service
      - DISCOVERY_SERVICE_PORT=${DISCOVERY_SERVICE_PORT}
      - USER_MICROSERVICE_DB_HOST=user-service-postgres-db
      - USER_MICROSERVICE_POSTGRES_PORT=${USER_MICROSERVICE_POSTGRES_PORT}
      - USER_MICROSERVICE_POSTGRES_USER=${USER_MICROSERVICE_POSTGRES_USER}
      - USER_MICROSERVICE_POSTGRES_PASSWORD=${USER_MICROSERVICE_POSTGRES_PASSWORD}
      - USER_MICROSERVICE_POSTGRES_DB=${USER_MICROSERVICE_POSTGRES_DB}
    restart: unless-stopped
    depends_on:
      config-service:
        condition: service_healthy

      discovery-service:
        condition: service_healthy

      user-service-postgres-db:
        condition: service_healthy

    networks:
      - pcforum_network

  notification-service:
    image: dawid0604/pcforum-notification-service-application
    container_name: notification-service
    environment:
      - CONFIG_SERVICE_INSTANCE=config-service
      - CONFIG_SERVICE_PORT=${CONFIG_SERVICE_PORT}
      - DISCOVERY_SERVICE_INSTANCE=discovery-service
      - DISCOVERY_SERVICE_PORT=${DISCOVERY_SERVICE_PORT}
      - NOTIFICATION_MICROSERVICE_DB_HOST=notification-service-postgres-db
      - NOTIFICATION_MICROSERVICE_POSTGRES_PORT=${NOTIFICATION_MICROSERVICE_POSTGRES_PORT}
      - NOTIFICATION_MICROSERVICE_POSTGRES_USER=${NOTIFICATION_MICROSERVICE_POSTGRES_USER}
      - NOTIFICATION_MICROSERVICE_POSTGRES_PASSWORD=${NOTIFICATION_MICROSERVICE_POSTGRES_PASSWORD}
      - NOTIFICATION_MICROSERVICE_POSTGRES_DB=${NOTIFICATION_MICROSERVICE_POSTGRES_DB}
    restart: unless-stopped
    depends_on:
      config-service:
        condition: service_healthy

      discovery-service:
        condition: service_healthy

      notification-service-postgres-db:
        condition: service_healthy

      kafka:
        condition: service_healthy

    networks:
      - pcforum_network

  thread-service:
    image: dawid0604/pcforum-thread-service-application
    container_name: thread-service
    environment:
      - CONFIG_SERVICE_INSTANCE=config-service
      - CONFIG_SERVICE_PORT=${CONFIG_SERVICE_PORT}
      - DISCOVERY_SERVICE_INSTANCE=discovery-service
      - DISCOVERY_SERVICE_PORT=${DISCOVERY_SERVICE_PORT}
      - THREAD_MICROSERVICE_DB_HOST=thread-service-postgres-db
      - THREAD_MICROSERVICE_POSTGRES_PORT=${THREAD_MICROSERVICE_POSTGRES_PORT}
      - THREAD_MICROSERVICE_POSTGRES_USER=${THREAD_MICROSERVICE_POSTGRES_USER}
      - THREAD_MICROSERVICE_POSTGRES_PASSWORD=${THREAD_MICROSERVICE_POSTGRES_PASSWORD}
      - THREAD_MICROSERVICE_POSTGRES_DB=${THREAD_MICROSERVICE_POSTGRES_DB}
    restart: unless-stopped
    depends_on:
      config-service:
        condition: service_healthy

      discovery-service:
        condition: service_healthy

      thread-service-postgres-db:
        condition: service_healthy

      kafka:
        condition: service_healthy

    networks:
      - pcforum_network

  post-service:
    image: dawid0604/pcforum-post-service-application
    container_name: post-service
    environment:
      - CONFIG_SERVICE_INSTANCE=config-service
      - CONFIG_SERVICE_PORT=${CONFIG_SERVICE_PORT}
      - DISCOVERY_SERVICE_INSTANCE=discovery-service
      - DISCOVERY_SERVICE_PORT=${DISCOVERY_SERVICE_PORT}
      - POST_MICROSERVICE_DB_HOST=post-service-postgres-db
      - POST_MICROSERVICE_POSTGRES_PORT=${POST_MICROSERVICE_POSTGRES_PORT}
      - POST_MICROSERVICE_POSTGRES_USER=${POST_MICROSERVICE_POSTGRES_USER}
      - POST_MICROSERVICE_POSTGRES_PASSWORD=${POST_MICROSERVICE_POSTGRES_PASSWORD}
      - POST_MICROSERVICE_POSTGRES_DB=${POST_MICROSERVICE_POSTGRES_DB}
    restart: unless-stopped
    depends_on:
      config-service:
        condition: service_healthy

      discovery-service:
        condition: service_healthy

      post-service-postgres-db:
        condition: service_healthy

      kafka:
        condition: service_healthy

    networks:
      - pcforum_network

networks:
  pcforum_network:
    driver: bridge
    name: pcforum_network