package pl.dawid0604.pcforum.category.service.persistence;

import com.aventrix.jnanoid.jnanoid.NanoIdUtils;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import jakarta.persistence.Column;
import jakarta.persistence.ColumnResult;
import jakarta.persistence.ConstructorResult;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedNativeQuery;
import jakarta.persistence.PrePersist;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.SqlResultSetMapping;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

import static jakarta.persistence.FetchType.LAZY;
import static jakarta.persistence.GenerationType.SEQUENCE;
import static lombok.AccessLevel.PACKAGE;

/**
 * Entity that represents Thread category.
 *
 * @see lombok.Lombok
 * @see NanoIdUtils
 * @see AuditingEntityListener
 * @see EntityListeners
 */
@SqlResultSetMapping(
        name = "CategoryEntity.default.mapping",
        classes = {
                @ConstructorResult(
                        targetClass = CategoryEntity.class,
                        columns = {
                                @ColumnResult(name = "id", type = long.class),
                                @ColumnResult(name = "public_id", type = String.class),
                                @ColumnResult(name = "name", type = String.class),
                                @ColumnResult(name = "icon_path", type = String.class),
                                @ColumnResult(name = "description", type = String.class),
                                @ColumnResult(name = "parent_id", type = Long.class)
                        }
                )
        }
)
@NamedNativeQuery(
        name = "CategoryEntity.findAllCustom",
        resultSetMapping = "CategoryEntity.default.mapping",
        query = """
                    SELECT id as id,
                           public_id as public_id,
                           name as name,
                           icon_path as icon_path,
                           description as description,
                           parent_id as parent_id
                    FROM categories
                """
)
@NamedNativeQuery(
        name = "CategoryEntity.findByParentId",
        resultSetMapping = "CategoryEntity.default.mapping",
        query = """
                   WITH RECURSIVE category_tree AS (
                        SELECT id as id,
                               public_id as public_id,
                               name as name,
                               icon_path as icon_path,
                               description as description,
                               parent_id as parent_id
                        FROM categories
                        WHERE public_id = :categoryId
    
                        UNION ALL
    
                        SELECT c.id,
                               c.public_id,
                               c.name,
                               c.icon_path as icon_path,
                               c.description,
                               c.parent_id
                        FROM categories c
                        INNER JOIN category_tree ct
                              ON ct.id = c.parent_id
                    )

                    SELECT * FROM category_tree
                """
)
@Entity
@Getter
@Builder
@EqualsAndHashCode
@Table(name = "categories")
@NoArgsConstructor(access = PACKAGE)
@SuppressFBWarnings("EI_EXPOSE_REP2")
@AllArgsConstructor(access = PACKAGE)
@EntityListeners(AuditingEntityListener.class)
public class CategoryEntity {

    /**
     * The unique category ID, generated by sequence.
     */
    @Id
    @Setter(PACKAGE)
    @Column(
            name = "id",
            updatable = false
    )
    @GeneratedValue(
            strategy = SEQUENCE,
            generator = "category_id_sequence"
    )
    @SequenceGenerator(
            name = "category_id_sequence",
            sequenceName = "category_id_sequence",
            allocationSize = 1
    )
    @SuppressWarnings("PMD.ShortVariable")
    private Long id;

    /**
     * Unique ID for use outside the application.
     * It's not updatable and cannot be nullable.
     */
    @Setter(PACKAGE)
    @Column(
            name = "public_id",
            unique = true,
            updatable = false,
            nullable = false
    )
    private String publicId;

    /**
     * The name of category. It must be unique and not nullable.
     */
    @Setter(PACKAGE)
    @Column(
            name = "name",
            unique = true,
            nullable = false
    )
    private String name;

    /**
     * The short description of category.
     */
    @Setter(PACKAGE)
    @Column(name = "description")
    private String description;

    /**
     * The category characteristic icon.
     */
    @Setter(PACKAGE)
    @Column(name = "icon_path")
    private String iconPath;

    /**
     * The parent category. Hierarchical relationship.
     */
    @Setter(PACKAGE)
    @ManyToOne(fetch = LAZY)
    @EqualsAndHashCode.Exclude
    @JoinColumn(name = "parent_id")
    @SuppressFBWarnings("EI_EXPOSE_REP")
    private CategoryEntity parent;

    /**
     * Auditing field that indicates founder.
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false)
    private String createdBy;

    /**
     * Auditing field that indicates user who modified this entity.
     */
    @LastModifiedBy
    @Column(name = "modified_by")
    private String modifiedBy;

    /**
     * Auditing field that indicates creation date.
     */
    @CreatedDate
    @Column(name = "created_date", updatable = false)
    private Instant createdDate;

    /**
     * Auditing field that indicates last modified date.
     */
    @LastModifiedDate
    @Column(name = "last_modified_date")
    private Instant lastModifiedDate;

    /**
     * Method to generate public_id if it's not present.
     */
    @PrePersist
    @SuppressWarnings("unused")
    void generatePublicId() {
        if (this.publicId == null) {
            this.publicId = NanoIdUtils.randomNanoId();
        }
    }

    /**
     * <p>
     *     Constructor used by {@link SqlResultSetMapping} with
     *     name {@code CategoryEntity.default.mapping}.
     * </p>
     * @param incomingId value from query
     * @param incomingPublicId value generated via {@link NanoIdUtils} from query
     * @param incomingName value from query
     * @param incomingIconPath value from query
     * @param incomingDescription value from query
     * @param incomingParentId value from query, can be null
     */
    @SuppressWarnings("unused")
    CategoryEntity(final long incomingId, final String incomingPublicId, final String incomingName,
                   final String incomingIconPath, final String incomingDescription,
                   final Long incomingParentId) {

        this.id = incomingId;
        this.publicId = incomingPublicId;
        this.name = incomingName;
        this.description = incomingDescription;
        this.iconPath = incomingIconPath;

        if (incomingParentId != null) {
            this.parent = CategoryEntity.builder()
                                        .id(incomingParentId)
                                        .build();
        }
    }
}
