name: Dockerize

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dockerize:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images and publish for all modules
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

        run: |
          set -e
          DATE=$(date +%Y%m%d)
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_NAME_CLEAN=$(echo "$BRANCH_NAME" | tr '/' '-')
          TAG="${BRANCH_NAME_CLEAN}-${DATE}-${GITHUB_SHA::7}"
     
          for pom in $(find services -mindepth 2 -maxdepth 3 -type d -name application); do
          DIR=$(dirname "$pom")
          MODULE=$(basename "$DIR")
          
          mvn -pl "$pom" clean compile jib:build -am -DskipTests \
           -Dimage=${DOCKERHUB_USERNAME}/pcforum-${MODULE}:${TAG} \
           -Ddocker.publishRegistry.username=${DOCKERHUB_USERNAME} \
           -Ddocker.publishRegistry.password=${DOCKERHUB_TOKEN}
          done
